# Generated by Django 5.1.4 on 2026-08-11 15:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.CharField(max_length=64, primary_key=True, serialize=False)),
                ('client_name', models.CharField(blank=True, default='', max_length=200)),
                ('client_id', models.CharField(blank=True, default='', max_length=200)),
                ('subject', models.CharField(blank=True, default='', max_length=300)),
                ('message', models.TextField(blank=True, default='')),
                ('status', models.CharField(default='OUVERT', max_length=20)),
                ('date_string', models.CharField(blank=True, default='', max_length=60)),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created'],
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.CharField(max_length=64, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('password', models.CharField(max_length=255)),
                ('role', models.CharField(default='client', max_length=20)),
                ('level', models.IntegerField(default=1)),
                ('avatar', models.CharField(blank=True, default='', max_length=20)),
                ('whatsapp', models.CharField(blank=True, default='', max_length=50)),
                ('birth_date', models.CharField(blank=True, default='', max_length=30)),
                ('profession', models.CharField(blank=True, default='', max_length=120)),
                ('residence', models.CharField(blank=True, default='', max_length=200)),
                ('kyc', models.CharField(default='pending', max_length=20)),
                ('email_verified', models.BooleanField(default=False)),
                ('balance', models.FloatField(default=0.0)),
                ('portfolio_value', models.FloatField(default=0.0)),
                ('joined_at', models.CharField(blank=True, default='', max_length=40)),
                ('identity_doc_status', models.CharField(blank=True, default='', max_length=30)),
                ('proof_of_address_status', models.CharField(blank=True, default='', max_length=30)),
                ('signature_status', models.CharField(blank=True, default='', max_length=30)),
                ('cni_recto_url', models.CharField(blank=True, max_length=300, null=True)),
                ('cni_verso_url', models.CharField(blank=True, max_length=300, null=True)),
                ('selfie_url', models.CharField(blank=True, max_length=300, null=True)),
                ('proof_address_url', models.CharField(blank=True, max_length=300, null=True)),
                ('contract_url', models.CharField(blank=True, max_length=300, null=True)),
                ('documents', models.JSONField(blank=True, default=dict)),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.CharField(max_length=64, primary_key=True, serialize=False)),
                ('user_email', models.CharField(blank=True, default='', max_length=200)),
                ('user_name', models.CharField(blank=True, default='', max_length=200)),
                ('ticker', models.CharField(blank=True, default='', max_length=20)),
                ('company', models.CharField(blank=True, default='', max_length=200)),
                ('type', models.CharField(max_length=20)),
                ('quantity', models.IntegerField(default=0)),
                ('price', models.FloatField(default=0.0)),
                ('total', models.FloatField(default=0.0)),
                ('fees', models.FloatField(default=0.0)),
                ('tva', models.FloatField(default=0.0)),
                ('grand_total', models.FloatField(default=0.0)),
                ('status', models.CharField(default='pending', max_length=20)),
                ('payment_ref', models.CharField(blank=True, default='', max_length=120)),
                ('payment_method', models.CharField(blank=True, default='', max_length=120)),
                ('rejection_reason', models.CharField(blank=True, max_length=300, null=True)),
                ('submitted_at', models.CharField(blank=True, default='', max_length=40)),
                ('processed_at', models.CharField(blank=True, max_length=40, null=True)),
                ('processed_by', models.CharField(blank=True, max_length=64, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='api.user')),
            ],
            options={
                'ordering': ['-created'],
            },
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.CharField(max_length=64, primary_key=True, serialize=False)),
                ('user_name', models.CharField(blank=True, default='', max_length=200)),
                ('sender', models.CharField(default='ADMIN', max_length=20)),
                ('text', models.TextField(blank=True, default='')),
                ('time', models.CharField(blank=True, default='', max_length=10)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='api.user')),
            ],
            options={
                'ordering': ['created'],
            },
        ),
    ]
